# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inkwell < Formula
  desc "Cloud-backed journaling TUI built on Bubble Tea"
  homepage "https://github.com/phekno/inkwell"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/phekno/inkwell/releases/download/v0.1.1/inkwell_0.1.1_darwin_arm64.tar.gz"
    sha256 "a1b6aca101fa8e7cbaebe0f952e9cd30d90f0c5dbd5485c2f8988b8dfa269cab"

    define_method(:install) do
      bin.install "inkwell"
    end
  end

  test do
    assert_match "inkwell", shell_output("#{bin}/inkwell --version", 0)
  end
end
