# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inkwell < Formula
  desc "Cloud-backed journaling TUI built on Bubble Tea"
  homepage "https://github.com/phekno/inkwell"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/phekno/inkwell/releases/download/v0.1.0/inkwell_0.1.0_darwin_arm64.tar.gz"
    sha256 "64a55e3040a0378554a3bc9e1d329257be16edc5923ba6dc797fedcdb6123712"

    define_method(:install) do
      bin.install "inkwell"
    end
  end

  test do
    assert_match "inkwell", shell_output("#{bin}/inkwell --version", 0)
  end
end
